version: '2'

services:
    nginx:
            image: nginx:latest        # 端口映射
            ports:
                - "80:80"
                - "11010:11010"
                - "11011:11011"
                - "5200:5200"
            # 依赖关系 先跑php
            depends_on:
                - "php"
            # 数据卷
            volumes:            # 映射主机./conf.d目录到容器/etc/nginx/conf.d目录
                - "$PWD/conf.d:/etc/nginx/conf.d"
                - "$PWD/html:/usr/share/nginx/html"
            networks:
                - backend       # 容器名称
            container_name: "compose-nginx"
    php:
          build:
              context: .
          ports:
              - "9000:9000"
          volumes:
              - "$PWD/html:/var/www/html"
          networks:
              - backend
          container_name: "compose-php"
    mysql:
          image: mysql:5.7
          ports:
              - "3306:3306"
          # 环境变量
          environment:            # mysql密码
              - MYSQL_ROOT_PASSWORD=123456
          networks:
              - backend
          container_name: "compose-mysql"
    redis:
          image: redis:latest
          ports:
              - "6379:6379"
          volumes:
                  - ./conf/redis.conf:/etc/redis.conf:ro
          restart: always
          #entrypoint: ["redis-server", "/etc/redis.conf"]
          command:
              redis-server
          networks:
              - backend
          container_name: "compose-redis"
    elasticsearch:
          image: elasticsearch:7.1.1
          container_name: "compose-elasticsearch"
          environment:
              - discovery.type=single-node
              - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
          volumes:
              - ./esdata:/usr/share/elasticsearch/data
          hostname: elasticsearch
          restart: always
          ports:
              - "9200:9200"
              - "9300:9300"

networks:
    backend:
          driver: bridge   