version: '3'

services:
        nginx:
                image: nginx:latest        # 端口映射
                ports:
                    - "80:80"
                # 依赖关系 先跑php
                depends_on:
                    - "php"
                # 数据卷
                volumes:            # 映射主机./conf.d目录到容器/etc/nginx/conf.d目录
                    - "$PWD/conf.d:/etc/nginx/conf.d"
                    - "$PWD/html:/usr/share/nginx/html"
                networks:
                    - backend       # 容器名称
                container_name: "compose-nginx"
        php:
              build: ./php-mysqli        # image指定build Dockerfile生成镜像的名称
              image: php:7.2-fpm-mysqli
              ports:
                  - "9000:9000"
              volumes:
                  - "$PWD/html:/var/www/html"
              networks:
                  - backend
              container_name: "compose-php"
        mysql:
              image: mysql:5.7
              ports:
                  - "3306:3306"
              # 环境变量
              environment:            # mysql密码
                  - MYSQL_ROOT_PASSWORD=123456
              networks:
                  - backend
              container_name: "compose-mysql"

        networks:
              backend:
                      driver: bridge   