version: '2'

services:
    nginx:
            image: nginx:latest        # 端口映射
            ports:
                - "80:80"
            # 依赖关系 先跑php
            depends_on:
                - "php"
            # 数据卷
            volumes:            # 映射主机./conf.d目录到容器/etc/nginx/conf.d目录
                - "$PWD/conf.d:/etc/nginx/conf.d"
                - "$PWD/html:/usr/share/nginx/html"
            networks:
                - backend       # 容器名称
            container_name: "compose-nginx"
    php:
          build:
              context: .
          ports:
              - "9000:9000"
          volumes:
              - "$PWD/html:/var/www/html"
          networks:
              - backend
          container_name: "compose-php"
    mysql:
          image: mysql:5.7
          ports:
              - "3306:3306"
          # 环境变量
          environment:            # mysql密码
              - MYSQL_ROOT_PASSWORD=123456
          networks:
              - backend
          container_name: "compose-mysql"
    redis:
          image: redis:latest
          ports:
              - "6379:6379"
          command:
              redis-server
          networks:
              - backend
          container_name: "compose-redis"

networks:
    backend:
          driver: bridge   